AWSTemplateFormatVersion: "2010-09-09"
Description: "Consensys Test UI hosting with S3 and CloudFront"
Parameters:
  EnvironmentName:
    Description: "Deployment environment"
    Type: String
    Default: "staging"
  DefaultRootObject:
    Description: "The default path for the index document."
    Type: String
    Default: "index.html"
  CertificateARN:
    Description: "ARN for SSL Certificate"
    Type: String
    Default: "arn:aws:acm:eu-west-1:593263191272:certificate/25a14cff-8a43-42c7-8515-543b9fe65b04"
  Subdomain:
    Description: "Name of the subdomain to user e.g. staging staging.edofoco.com"
    Type: String
    Default: consensys-test.staging
Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub consensys-test-ui-${EnvironmentName}

  ReadPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Action: "s3:GetObject"
            Effect: Allow
            Resource: !Sub "arn:aws:s3:::${S3Bucket}/*"
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId

  CloudFrontOriginAccessIdentity:
    Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref S3Bucket

  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub ${Subdomain}.edofoco.com
          - !Sub www.${Subdomain}.edofoco.com
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: "/index.html"
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: "/index.html"
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          DefaultTTL: 3600
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          MaxTTL: 86400
          MinTTL: 60
          TargetOriginId: s3origin
          ViewerProtocolPolicy: "redirect-to-https"
        DefaultRootObject: !Ref DefaultRootObject
        Enabled: true
        HttpVersion: http2
        Origins:
          - DomainName: !GetAtt "S3Bucket.DomainName"
            Id: s3origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}"
        PriceClass: "PriceClass_All"
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateARN
          SslSupportMethod: "sni-only"

Outputs:
  BucketName:
    Description: "S3 Bucket Name"
    Value: !Ref S3Bucket
  DistributionId:
    Description: "CloudFront Distribution ID"
    Value: !Ref CloudFrontDistribution
  Domain:
    Description: "Cloudfront Domain"
    Value: !GetAtt CloudFrontDistribution.DomainName
